[passwords]
shivaanh = "streamlit12"
ellisf = "streamlit12"
marlenec = "streamlit12"
andred = "streamlit12"
aprilj = "streamlit12"
kirshwans = "streamlit12"

[google]
type = "service_account"
project_id = "foilworx-jobs"
private_key_id = "a1c40584bb84c5ccac880a32eb92cbb1b254688d"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCzAFY2tCyvnE9X\n+J7XeObxyc3Ee5y5iuPPYlOFDz8u9oZLCQdUhgUuwOO5HiHFP3x9zUv/vyp+K4Z3\nVza4cZSylyPcTgP3oFsCwFA00f5xzZdfXx9C9dl8seqs/ZaDPIO9dbuXhaSzev3n\ns+EoRiJRLNEnXzMm6ztaxUet3M1gdA9KUmkk5Q+QXEkcjNWCFQhz9wQszf7qgwrD\nh4eHDzo08YpFMgH5+wmnQjBZKOeWvKaftR9JHnpus3gafnQPdj3e2Lq875D85Bfz\ntlAf7Fll2x8nuBo1jU26f3WmS3fFPTX/BsHWFHIF/EeYBNic6yiFFoU7aMlVUP4a\nEpiLWOXPAgMBAAECggEAMhNgCwGwlpgl4jhdR249PVr1Q4hJOebPAE9Dii/PvzWc\nMBWghVbQ0FmJ21nAnMu76f2qyysRmiZXAb/WQRcVQDjkAVeZ6IZlr4lZZs1wXyni\ntP2JY1QfubCUNDzlBGXDfRcYmbT7dHJt4YoC7R9hrk/ZWyhYyQR5oFUcTlk840Rb\nTpMnVxyEyd6fjMuMSQ+q5aJmx5yTHnikehCx+loejg7J2WzyPdePAT1eRnYSpTQX\nQfEWOTn1cnwfdPkDkXdJHFUNf4N0yy1xoY66zQf7LpBibNy5tQSyXP5yP1039DtN\nQITGPBHVF24c3Y3zYl3qkbPyYyiapru9Gc8bJ2XqEQKBgQD7EI23ZbhWY5736V3U\nBDwrdPkusSPb5i+hLTCuki3rKyvQSO9hrPQM0gIMCQ94aE88eFRZc+K9X43u3puj\nnOPzJOhjdHd5xFquFz4XY74pSqm122qq0e/FdG6l66sd31Lmo3XCRmTmoTOi4tMQ\nPvImqkot5lYv9rPxUTevG/rjywKBgQC2hSKHGYSi98yvSqd+Fw0dJwUIeeoMvryn\nPRIQg+OdLGHV6J3zHoFDz3bwn68v92cDW1gOt1JgltGBvAFNWuDI2L08/x8V3x0T\nhvRSJrxw+Kd/ZfNdb6VcPQGaK0nRNO3V/h/xOStTTNWKi6ge/WnYHDjjpXVgfjh2\nPY5aQARtjQKBgEDaYNEsDHb8WtcNSDh5M5XCLI/8IBgwmMMYqked6RCjYTj3biac\nB5q8MN0tBfsDbtxe9OL6hWqHoWE/zZJw940aTpFKR4aDyyzHQjnGgRundrlMSXyA\nqGAoGGDxxIz94CtFtCiQCIZuw6ji0MSUjfag7HJ42nCfWJIQecLZBnELAoGAOFzY\nkruwl9rJ3H/DRU68//mitkFfo1vrSgGz6GGyEkE4XSQeUotjA5u3cQr+wGM37nNw\nt+qoh6dLPzLdfBPKQnubxJBL+ycRBYyxOgU4P/KpVtAW3Q2zFM7KBd/ERdSAdYqq\nNoWe+XRKpSQHYLqEyvW8I6BepNOVf/32TaxjMakCgYBLzpSSmCecRoFC1ioSJnPD\n+wYjM82UFE1mdkYsbxR0r3EGr/nh016GWXviRtNuddm9v+KcnbSpRnSGeiSYWRl/\ne9ISNmLIzafOeNN1QKLib/p2mGky+Kav2omxWWls6Njki5B7CsuwmsBhfx2Af7Ys\naiwTmo4YSVLr+5Q6WV4egw==\n-----END PRIVATE KEY-----\n"
client_email = "foilworxsheet@foilworx-jobs.iam.gserviceaccount.com"
client_id = "109552501067968911635"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/foilworxsheet%40foilworx-jobs.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
